### PR TITLE
feat: Implement CEL validation

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
Thank you very much for this job.

Should I merge this PR and then push it upstream? @jimmidyson

**Comment by jimmidyson** [comment]
@chaunceyjiang If you merge this PR then it should automatically update the CAPI PR with CEL validation 🤞

**Comment by chaunceyjiang** [comment]
> @chaunceyjiang If you merge this PR then it should automatically update the CAPI PR with CEL validation 🤞

Ok.

**Comment by chaunceyjiang** [comment]
Hello, @jimmidyson, if you're ready to merge, feel free to cc me anytime. I will come and merge this PR. Thank you very much~

**Pull request merged**
